// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOr1on7mUGwO4mRSAGwvy9wgC8dVWoEY',
    appId: '1:470547192109:web:45e3cb672dc1b368091ba4',
    messagingSenderId: '470547192109',
    projectId: 'butikdatabase',
    authDomain: 'butikdatabase.firebaseapp.com',
    databaseURL: 'https://butikdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'butikdatabase.firebasestorage.app',
    measurementId: 'G-EM0SYY9PFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LEbpY4METhbyq_GKtv_YQ1XxJkaTtL0',
    appId: '1:470547192109:android:3e99706d810f1dcd091ba4',
    messagingSenderId: '470547192109',
    projectId: 'butikdatabase',
    databaseURL: 'https://butikdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'butikdatabase.firebasestorage.app',
  );
}
